#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

"$XDG_CONFIG_HOME"/polybar/launch.sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config split_ratio 0.5
bspc config border_width 3
bspc config window_gap 10

bspc config focused_border_color "#c4a7e7"
bspc config normal_border_color "#6e6a86"
bspc config active_border_color "#6e6a86"
bspc config presel_feedback_color "#403d52"

bspc rule -a mpv state=floating layer=normal center=true
